[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "java -Dspring.profiles.active=production -jar target/fixpoint-0.0.1-SNAPSHOT.jar"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10
