[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "java -jar target/fixpoint-0.0.1-SNAPSHOT.jar"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[environments.production.variables]
  SPRING_PROFILES_ACTIVE = "production"
