-- Migration script to change DESCRIPTION column from VARCHAR(2000) to TEXT
-- This script should be run on the H2 database

-- First, let's check the current structure
-- SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH 
-- FROM INFORMATION_SCHEMA.COLUMNS 
-- WHERE TABLE_NAME = 'REPORTS' AND COLUMN_NAME = 'DESCRIPTION';

-- Alter the column to remove length limitation
ALTER TABLE REPORTS ALTER COLUMN DESCRIPTION SET DATA TYPE TEXT;

-- Verify the change
SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'REPORTS' AND COLUMN_NAME = 'DESCRIPTION';
